name: vpass
description: A password generator.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.3+5

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color:    #nÃ£o funciona
  crypto: ^3.0.2
  convert: ^3.1.1
  shared_preferences: ^2.1.0
  google_mobile_ads: ^3.0.0  #nÃ£o funciona
  package_info_plus: ^4.0.0
  fluttericon: ^2.0.0
  url_launcher: ^6.1.10
  material_color_utilities: 
  flutter_launcher_icons: ^0.13.1 #nÃ£o funciona
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.0


flutter:
  uses-material-design: true
  fonts:
  - family: ShareTechMono
    fonts:
    - asset: assets/fonts/ShareTechMono-Regular.ttf
  - family: Ubuntu
    fonts:
    - asset: assets/fonts/Ubuntu-Regular.ttf
